# Generated by Django 5.0.2 on 2024-06-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
